name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version'     
        required: true
        type: string

env:
  CARGO_TERM_COLOR: always

jobs:
  Build:

    runs-on: macOS-12

    steps:
      - name: Setup enviornment
        run: |
          rustup target install aarch64-apple-ios
          cargo install cargo-lipo
      
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
          
      - name: Make lib
        run: |
          cd tun2socks
          cargo lipo --release --package tun2socks --targets "aarch64-apple-ios"
          
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          tag_name: ${{ github.event.inputs.version }}
          files: tun2socks/target/universal/release/libtun2socks.a
